
import React from 'react';
import { cn } from '@/lib/utils';

const AboutSection: React.FC = () => {
  return (
    <section id="about" className="py-24 px-4">
      <div className="container max-w-5xl mx-auto">
        <div className="flex flex-col md:flex-row gap-12">
          <div className="md:w-1/2">
            <h2 className="text-3xl md:text-4xl font-bold mb-6">About Edge Mining</h2>
            
            <p className="text-muted-text text-lg leading-relaxed mb-6">
              Edge Mining is a FOSS project that integrates Bitcoin mining with renewable energy systems. Designed for small and medium-sized power plants, it helps turn excess energy into economic value.
            </p>
            
            <p className="text-muted-text text-lg leading-relaxed">
              Mining is automated based on energy availability, and the heat generated by the miners can be reused for space heating—maximizing overall energy efficiency.
            </p>
          </div>
          
          <div className="md:w-1/2 bg-dark-accent rounded-lg p-8">
            <h3 className="text-xl font-semibold mb-4">Key Features</h3>
            
            <ul className="space-y-4">
              <li className="flex items-start">
                <div className="mr-4 mt-1 bg-white/10 rounded-full p-1">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <polyline points="20 6 9 17 4 12"></polyline>
                  </svg>
                </div>
                <span className="text-muted-text">Automated mining based on energy availability</span>
              </li>
              <li className="flex items-start">
                <div className="mr-4 mt-1 bg-white/10 rounded-full p-1">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <polyline points="20 6 9 17 4 12"></polyline>
                  </svg>
                </div>
                <span className="text-muted-text">Heat recovery for space heating</span>
              </li>
              <li className="flex items-start">
                <div className="mr-4 mt-1 bg-white/10 rounded-full p-1">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <polyline points="20 6 9 17 4 12"></polyline>
                  </svg>
                </div>
                <span className="text-muted-text">Perfect for small and medium-sized power plants</span>
              </li>
              <li className="flex items-start">
                <div className="mr-4 mt-1 bg-white/10 rounded-full p-1">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <polyline points="20 6 9 17 4 12"></polyline>
                  </svg>
                </div>
                <span className="text-muted-text">Open-source and free to use</span>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </section>
  );
};

export default AboutSection;
