
import React from 'react';
import { cn } from '@/lib/utils';
import { Card, CardContent } from '@/components/ui/card';
import { CheckCircle } from 'lucide-react';

const AboutSection: React.FC = () => {
  return (
    <section id="about" className="py-24 px-4 relative overflow-hidden">
      {/* Background gradient */}
      <div className="absolute inset-0 bg-gradient-to-b from-dark to-dark-accent opacity-50 pointer-events-none"></div>
      <div className="absolute bottom-0 right-0 w-96 h-96 bg-accent/5 rounded-full filter blur-3xl"></div>
      
      <div className="container max-w-5xl mx-auto relative z-10">
        <div className="flex flex-col md:flex-row gap-12">
          <div className="md:w-1/2">
            <h2 className="font-display text-3xl md:text-4xl font-bold mb-6 text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-accent">
              About Edge Mining
            </h2>
            
            <p className="text-muted-text text-lg leading-relaxed mb-6">
              Edge Mining is a FOSS project that integrates Bitcoin mining with renewable energy systems. Designed for small and medium-sized power plants, it helps turn excess energy into economic value.
            </p>
            
            <p className="text-muted-text text-lg leading-relaxed">
              Mining is automated based on energy availability, and the heat generated by the miners can be reused for space heating—maximizing overall energy efficiency.
            </p>
          </div>
          
          <div className="md:w-1/2">
            <Card className="glass-effect shadow-xl shadow-accent/5 border-accent/20">
              <CardContent className="p-8">
                <h3 className="font-display text-xl font-semibold mb-6 text-white">Key Features</h3>
                
                <ul className="space-y-4">
                  {[
                    "Automated mining based on energy availability",
                    "Heat recovery for space heating",
                    "Perfect for small and medium-sized power plants",
                    "Open-source and free to use"
                  ].map((feature, index) => (
                    <li key={index} className="flex items-start group">
                      <div className="mr-4 mt-1 text-accent group-hover:text-accent/80 transition-standard">
                        <CheckCircle size={18} />
                      </div>
                      <span className="text-light-text group-hover:text-white transition-standard">{feature}</span>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </section>
  );
};

export default AboutSection;
